name: PullRequest
description: Create a new pull request
projects: ["tiki/1"]
body:
  - type: textarea
    id: issues
    attributes:
      label: Linked Issues
      description: Link each issue addressed by the PR
      value: |
        e.g. Resolves #10, resolves #123, resolves octo-org/octo-repo#100
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Information
      description: Add anything else that might be helpful to understanding the PR.
    validations:
      required: false
