# Reference: https://github.com/repository-settings/app

repository:
  has_issues: false
  has_projects: false
  has_discussions: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage

labels:
  - name: breaking
    color: D73A4A
    description: Introduces a breaking change.
  - name: critical
    color: D73A4A
    description: Stop what you're doing and fix it, now.
  - name: blocked
    color: D73A4A
    description: Something is blocking this.
  - name: bug
    color: FFB8C6
    description: Something isn't working.
  - name: chore
    color: FEF2C0
    description: Naming, organizing folder structure, and less impactful tasks.
  - name: docs
    color: FEF2C0
    description: Related to documentation and information.
  - name: feature
    color: 5EBEFF
    description: Brand new functionality, features, pages, workflows, endpoints, etc.
  - name: fix
    color: 91CA55
    description: Iterations on existing features or infrastructure.
  - name: security
    color: D73A4A
    description: Something is vulnerable or not secure.
  - name: testing
    color: 64CFDB
    description: Related to testing.
  - name: duplicate
    color: FFFFFF
    description: This issue or pull request already exists.
  - name: invalid
    color: FFFFFF
    description: Not a valid issue. It likely belongs in discussions.
  - name: story
    color: FFFFFF
    description: For project tracking only. This issue is a User Story.
  - name: task
    color: FFFFFF
    description: For project tracking only. This issue is a Task for a User Story.

branches:
  - name: main
    protection:
      allow_deletions: false
      allow_force_pushes: false
      allow_fork_syncing: false
      block_creations: true
      enforce_admins: false
      lock_branch: false
      required_conversation_resolution: true
      required_linear_history: false
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        dismissal_restrictions:
          teams: ["sysadmin"]
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        required_approving_review_count: 1
      restrictions: null

environments:
  - name: production
    deployment_branch_policy:
      protected_branches: true
