# Reference: https://github.com/repository-settings/app

repository:
  has_issues: true
  has_projects: false
  has_discussions: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage

labels:
  - name: blocked
    color: D73A4A
    description: Something is blocking this.
  - name: feature
    color: 5EBEFF
    description: Brand new functionality, features, pages, workflows, endpoints, etc.
  - name: fix
    color: 91CA55
    description: Iterations on existing features or infrastructure.
  - name: task
    color: FFFFFF
    description: For project tracking only. This issue is a Task for a Deliverable.
  - name: deliverable
    color: 326223
    description: This issue is a Deliverable. It should have a list of tasks that need to be completed.

branches:
  - name: main
    protection:
      allow_deletions: false
      allow_force_pushes: false
      allow_fork_syncing: false
      block_creations: true
      enforce_admins: false
      lock_branch: false
      required_conversation_resolution: true
      required_linear_history: false
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        dismissal_restrictions:
          teams: ["sysadmin"]
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        required_approving_review_count: 1
      restrictions: null

environments:
  - name: production
    deployment_branch_policy:
      protected_branches: true
