# Reference: https://github.com/repository-settings/app

repository:
  has_issues: true
  has_projects: false
  has_discussions: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

teams:
  - name: architecture
    permission: admin
  - name: backend
    permission: push
  - name: data
    permission: push
  - name: frontend
    permission: push
  - name: infrastructure
    permission: push

branches:
  - name: main
    protection:
      allow_deletions: false
      allow_force_pushes: false
      allow_fork_syncing: false
      block_creations: true
      enforce_admins: false
      lock_branch: false
      required_conversation_resolution: true
      required_linear_history: false
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        dismissal_restrictions:
          teams: ["sysadmin"]
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        required_approving_review_count: 1
      restrictions: null
  - name: develop
    protection:
      allow_deletions: false
      allow_force_pushes: false
      allow_fork_syncing: false
      block_creations: false
      enforce_admins: false
      lock_branch: false
      required_conversation_resolution: false
      required_linear_history: false
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        dismissal_restrictions:
          teams: ["sysadmin"]
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        required_approving_review_count: 1
      restrictions: null 

environments:
  - name: production
    deployment_branch_policy:
      protected_branches: true
  - name: staging
    deployment_branch_policy:
      protected_branches: true
 
labels:
  - name: release
    color: 326223
    description: This issue is a Release.
  - name: feature
    color: 5EBEFF
    description: A feature deliverable.
  - name: fix
    color: 91CA55
    description: A fix deliverable.
  - name: refactor  
    description: A code change that neither fixes a bug nor adds a feature. 
    color: 19e7cf
  - name: ci
    color: 5319E8
    description: Continuous Integration tasks.
  - name: chore
    color: 497E76
    description: Changes to auxiliary tools and libraries.
  - name: docs  
    color: 587246
    description: Documentation only changes.
  - name: test  
    color: E1CC4F
    description: Adding missing tests.
  - name: style
    color: EA899A
    description: Changes that do not affect the meaning of the code.
  - name: data
    color: 6E5494
    description: Changes in the data processing scripts.