backend:
  description: The engineers who build the systems that keep everything running, even if no one sees them or says thanks.
  members:
    - github: TarsioGomides
    - github: MiroBenicio

data:
  description: The data plumbers, tidying up messy datasets and making sure everything flows in neat, organized rows.
  members:
    - github: mariananunes-data

frontend:
  description: The creators of the tools customers love, making sure every click feels seamless.
  members:
    - github: MiroBenicio
    - github: juan-alencar

infrastructure:
  description: Digital construction crew, building the foundation and deciphering AWS docs.
  members:
    - github: TarsioGomides
    - github: barbarabr1to

architecture:
  description: The architects and gatekeepers, designing what others build and making sure it all runs smoothly—while they figure out how to build it.
  members:
    - github: mike-audi
    - github: ricardobrg
