backend:
  description: Those who build the infrastructure.
  members:
    - github: mike-audi
    - github: ricardobrg
    - github: TarsioGomides

frontend:
  description: Those who build the tools customers touch.
  members:
    - github: MiroBenicio
    - github: ricardobrg
    - github: juan-alencar

sysadmin:
  description: Approval escalation and monitoring.
  members:
    - github: mike-audi
    - github: ricardobrg
