name: Milestone
description: Create a new milestone
title: "[Milestone Name]"
projects: ["tiki/1"]
labels:
  - milestone
assignees:
  - timoguin
body:
  - type: markdown
    attributes:
      value: |
        ### Nice! Let's open a milestone.**
        *As a reminder, milestones combine multiple issues into a single, released deliverable. If you're unsure, just open a normal story.*
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the milestone. Include key requirements, features, etc.
    validations:
      required: true
  - type: textarea
    id: issues
    attributes:
      label: Issues
      description: Add all issues required to complete the milestone as a task list.
      value: |
        - [ ] tiki/<repository_name>#<issue number>
    validations:
      required: true
  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm
      description: Are you in the right repo? Milestones belong in monorepos like apps, capture, publish, purchase, core, or website.
      options:
        - label: Yeah dude.
          required: true
