name: Story
description: Create a new story
title: "[Story Name]"
projects: ["tiki/1"]
body:
  - type: markdown
    attributes:
      value: |
        ### Nice! Let's open a new story.**
        *As a reminder, a story is like a task, small, but includes both the reason for the change and clear success criteria.*
  - type: input
    id: reason
    attributes:
      label: Reason
      description: Describe the reason for the change.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the requested change in your own words.
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: Success Criteria
      description: Describe what "done done" looks like.
      value: |
        - [ ] criteria 1
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Information
      description: Add anything else that might be helpful to complete the story like references or potential solutions.
    validations:
      required: false
