name: Task
description: Advanced! Leave this to the maintainers.
labels:
  - task
projects: ["tiki/9"]
type: task
body:
  - type: markdown
    attributes:
      value: |
        ### Time to get technical.
  - type: input
    id: deliverable
    attributes:
      label: Deliverable
      description: Add the deliverable this task belongs to.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the work with enough detail that someone else can understand what needs to be done.
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: Add any specific criteria required before marking as complete
      placeholder: |
        - [ ] criteria 1
    validations:
      required: true
