name: Dependabot

on: push

jobs:
#  get-org-repos:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: austenstone/get-org-repos@main
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          org: ${{ github.context.repo.owner }}
#        id: get-org-repos
#    outputs:
#      repos: ${{ steps.get-org-repos.outputs.repos }}

  create-issues:
#    needs: [ get-org-repos ]
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
#      fail-fast: false
    steps:
      - name: Get Dependabot PRs
        id: dependabot-prs
        run: echo "prs=$(gh pr list -R ${{ github.context.repo.owner }}/core-iceberg-metadata -A app/dependabot --json title,url)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create Table
        if: ${{ steps.dependabot-prs.outputs.prs != '[]' }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: ${{ steps.dependabot-prs.outputs.prs }}

      - name: Create issue
        uses: dacbd/create-issue-action@main
        id: new-issue
        with:
          token: ${{ github.token }}
          title: Review Dependabot PR
          body: ${{ steps.table.outputs.body }}
          labels: chore
          repo: core-iceberg-metadata

      - name: Issue Number
        id: issue-number
        run: |
          echo "number=$(${{ steps.new-issue.outputs.json }} | jq .number)" >> $GITHUB_OUTPUT

      - name: Add to project
        uses: monry/actions-add-issue-to-project@v2
        with:
          github-token: ${{ secrets.GH_PROJECT_PAT }}
          project-owner: ${{ github.context.repo.owner }}
          project-number: 1
          issue-repository: core-iceberg-metadata
          issue-number: ${{ steps.issue-number.outputs.number }}
