name: Dependabot

on: push

permissions:
  issues: write

jobs:
#  get-org-repos:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: austenstone/get-org-repos@main
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          org: ${{ github.context.repo.owner }}
#        id: get-org-repos
#    outputs:
#      repos: ${{ steps.get-org-repos.outputs.repos }}

  check-prs:
#    needs: [ get-org-repos ]
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
#      fail-fast: false
    outputs:
      prs: ${{ steps.dependabot-prs.outputs.prs }}
    steps:
      - name: Get Dependabot PRs
        id: dependabot-prs
        run: echo "prs=$(gh pr list -R tiki/core-iceberg-metadata -A app/dependabot --json title,url)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

  create-issue:
    needs: [check-prs]
    if: ${{ needs.check-prs.outputs.prs != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Table
        uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: ${{ steps.dependabot-prs.outputs.prs }}

      - name: Print Table
        run: echo ${{ steps.table.outputs.body }}

      - name: Create issue
        uses: dacbd/create-issue-action@main
        id: new-issue
        with:
          token: ${{ secrets.GH_PROJECT_PAT }}
          title: Review Dependabot PR
          body: ${{ steps.table.outputs.body }}
          labels: chore
          repo: core-iceberg-metadata
          owner: tiki

      - name: Issue Number
        id: issue-number
        run: |
          echo "${{ steps.new-issue.outputs.json }}" | jq

#      - name: Add to project
#        uses: monry/actions-add-issue-to-project@v2
#        with:
#          github-token: ${{ secrets.GH_PROJECT_PAT }}
#          project-owner: ${{ github.context.repo.owner }}
#          project-number: 1
#          issue-repository: core-iceberg-metadata
#          issue-number: ${{ steps.issue-number.outputs.number }}
