name: Dependabot

on:
  schedule:
    - cron: "0 5 * * 1"

env:
  ORG: tiki

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          org: ${{ env.ORG }}
        id: get-org-repos
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}

  check-prs:
    needs: [ get-org-repos ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - name: Get Dependabot PRs
        id: dependabot-prs
        run: |
          echo "prs=$(gh pr list -R ${{ env.ORG }}/${{ matrix.repo }} -A app/dependabot --json title,url)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_PAT }}

      - name: Create Table
        if: ${{ steps.dependabot-prs.outputs.prs != '[]' }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: ${{ steps.dependabot-prs.outputs.prs }}

      - name: Create issue
        if: ${{ steps.dependabot-prs.outputs.prs != '[]' }}
        uses: dacbd/create-issue-action@main
        id: new-issue
        with:
          token: ${{ secrets.GH_PROJECT_PAT }}
          title: Review Dependabot PR
          body: ${{ steps.table.outputs.table }}
          labels: chore
          repo: ${{ matrix.repo }}
          owner: ${{ env.ORG }}
