name: Dependabot

on: push

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          org: tiki
        id: get-org-repos
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}

  build:
    needs: [ get-org-repos ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - run: echo "Hello ${{ matrix.repo }}!"

#  create-issue:
#    if: ${{ github.event_name == 'pull_request' && needs.check-dependabot.outputs.dependabot == 'true'}}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Open issue
#        env:
#          pr_title: ${{github.event.pull_request.title}}
#          pr_number: ${{github.event.pull_request.number}}
#          pr_url: ${{github.event.pull_request.url}}
#          issue_labels: chore
#          gh_project:
#        run: |
#          title="$pr_title (#$pr_number)"
#          body="Dependabot has opened PR: $pr_url"
#          gh issue create --title "$title" --body "$body" --label "issue_labels" --project
